repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9  # This should match your pyproject.toml version
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --check-untyped-defs]
        additional_dependencies:
            - numpy
            - pandas
            - types-requests
